services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/cert:/etc/letsencrypt/live/
    restart: unless-stopped

  react:
    image: nginx:latest
    volumes:
      - ./react/build:/usr/share/nginx/html
      - ./react/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped

  spring:
    build: ./spring
    container_name: spring
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:10-alpine
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    restart: unless-stopped
