-- we don't know how to generate root <with-no-name> (class Root) :(

comment on database postgres is 'default administrative connection database';

create sequence group_seq
    increment by 50;

alter sequence group_seq owner to seunghun;

create sequence member_seq
    increment by 50;

alter sequence member_seq owner to seunghun;

create sequence member_authorities_seq
    increment by 50;

alter sequence member_authorities_seq owner to seunghun;

create sequence group_member_authorities_seq
    increment by 50;

alter sequence group_member_authorities_seq owner to seunghun;

create sequence member_group_seq
    increment by 50;

alter sequence member_group_seq owner to seunghun;

create sequence members_seq
    increment by 50;

alter sequence members_seq owner to seunghun;

create sequence group_membership_seq
    increment by 50;

alter sequence group_membership_seq owner to seunghun;

create sequence group_payments_seq
    increment by 50;

alter sequence group_payments_seq owner to seunghun;

create sequence groups_seq
    increment by 50;

alter sequence groups_seq owner to seunghun;

create sequence users_seq
    increment by 50;

alter sequence users_seq owner to seunghun;

create table groups
(
    created_time timestamp(6),
    group_id     bigint not null
        primary key,
    updated_time timestamp(6),
    description  varchar(255),
    image        varchar(255),
    name         varchar(255)
);

alter table groups
    owner to seunghun;

create table group_payments
(
    group_id         bigint
        constraint fk8y8mw1lmm9d5guec0tutecqnp
            references groups,
    group_payment_id bigint not null
        primary key,
    card_brand       varchar(255),
    card_number      varchar(255),
    card_owner       varchar(255)
);

alter table group_payments
    owner to seunghun;

create table users
(
    created_time timestamp(6),
    updated_time timestamp(6),
    user_id      bigint not null
        primary key,
    email        varchar(255)
        unique,
    password     varchar(255),
    user_image   varchar(255),
    username     varchar(255)
        unique
);

alter table users
    owner to seunghun;

create table group_membership
(
    created_time  timestamp(6),
    group_id      bigint
        constraint fksc4ykyti548dy9kso0bd3hxf
            references groups,
    membership_id bigint not null
        primary key,
    updated_time  timestamp(6),
    user_id       bigint
        constraint fk650cewn9xqbxdo98s53set6ht
            references users,
    authority     varchar(255)
        constraint group_membership_authority_check
            check ((authority)::text = ANY
        ((ARRAY ['OWNER'::character varying, 'ADMIN'::character varying, 'MEMBER'::character varying])::text[])),
    unique (user_id, group_id),
    constraint ukobekhxig3axb25sv7bd0kjp4l
        unique (user_id, group_id)
);

alter table group_membership
    owner to seunghun;

create table invitation
(
    group_id      bigint
        constraint fkor0jxj41fitqu2bfwldup688i
            references groups,
    invitation_id bigint generated by default as identity
        primary key,
    receiver_id   bigint
        constraint fkgnf21don63dhi6kd84yy9uqx2
            references users,
    sender_id     bigint
        constraint fk8qamsp0em5ub7edqfww44h3ix
            references users,
    status        varchar(255) not null
        constraint invitation_status_check
            check ((status)::text = ANY
        ((ARRAY ['PENDING'::character varying, 'ACCEPTED'::character varying, 'REJECTED'::character varying])::text[]))
    );

alter table invitation
    owner to seunghun;

create table project
(
    group_id     bigint
        constraint fkefoa112f5uoe238ithe2sqrf7
            references groups,
    owner_id     bigint
        constraint fk7tetln4r9qig7tp05lsdqe8xo
            references users,
    project_id   bigint generated by default as identity
        primary key,
    name         varchar(100) not null,
    description  varchar(255),
    domain       varchar(255),
    project_type varchar(255)
        constraint project_project_type_check
            check ((project_type)::text = ANY
        ((ARRAY ['PUBLIC'::character varying, 'PRIVATE'::character varying])::text[]))
    );

alter table project
    owner to seunghun;

create table project_authority
(
    id         bigint generated by default as identity
        primary key,
    project_id bigint
        constraint fk8r63p9g5qhs1ot7hll6fschyn
            references project,
    user_id    bigint
        constraint fk4f3enlnw35j86e7j8lmvp2wsc
            references users,
    permission varchar(255) not null
        constraint project_authority_permission_check
            check ((permission)::text = ANY ((ARRAY ['VIEW'::character varying, 'EDIT'::character varying])::text[])),
    unique (user_id, project_id),
    constraint ukpub17vh94sfmleibi45a3k19h
        unique (user_id, project_id)
);

alter table project_authority
    owner to seunghun;

create table project_image
(
    id         bigint generated by default as identity
        primary key,
    project_id bigint
        constraint fksrkbi9ax581cp14a13mbk9qtm
            references project,
    image      varchar(255)
);

alter table project_image
    owner to seunghun;

create table container_detail
(
    container_detail_id     bigint generated by default as identity
        primary key,
    container_domain        varchar(255),
    code_file_url           varchar(255),
    port                    bigint,
    project_id              bigint
        constraint fk9jx24gws34s62sf86pq1393f4
            references project,
    container_template_name varchar(255),
    container_stack         varchar(255),
    code_file_name          varchar(255)
);

alter table container_detail
    owner to seunghun;

create table container_env
(
    container_env_id bigint generated by default as identity
        primary key,
    env_key          varchar(255),
    container_id     bigint
        constraint fki6aq55u1u1t46r7beujefkpal
            references container_detail
);

alter table container_env
    owner to seunghun;

