spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 
    username: 
    password: 
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

  data:
    redis:
      host: 
      port: 6379
      password: 

  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/**

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

aws:
  access-key: 
  secret-key: 
